# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

workspace 'StencilLayout.xcworkspace'
project 'StencilLayout.xcodeproj'

target 'StencilLayout' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for freecard
  pod 'YYImage/WebP'
  pod 'YYWebImage'
end
